name : feministclickback
url: https://feministclickback.org
title: feministclickback.org
t:
  de:
    content:
      name: "Inhalt"
      url: "/#inhalt"
    glossary:
      name: "Glossar"
      url: "/glossar.html"
    dates:
      name: "Termine"
      url: "/termine.html"
    newsletter:
      name: "Newsletter"
      url: "/newsletter.html"
    download:
      name: "Download"
      url: "/assets/files/platz-nehmen_final_web.pdf"
    contact:
      name: "Kontakt"
      url: "/kontakt.html"
  en:
    content:
      name: "Content"
      url: "/en/#content"
    glossary:
      name: "Glossary"
      url: "/en/glossary.html"
    dates:
      name: "Dates"
      url: "/en/dates.html"
    newsletter:
      name: "Newsletter"
      url: "/en/newsletter.html"
    download:
      name: "Download"
      url: "/assets/files/platz-nehmen_final_web.pdf"
    contact:
      name: "Contact"
      url: "/en/contact.html"
