name : feministclickback
url: https://feministclickback.org
title: feministclickback.org
t:
  de:
    glossary:
      name: "Glossar"
      url: "/glossar.html"
    download:
      name: "Download"
      url: "/assets/files/feministclickback-broschuere-2018.pdf"
    contact:
      name: "Kontakt"
      url: "/kontakt.html"
  en:
    glossary:
      name: "Glossary"
      url: "/en/glossary.html"
    download:
      name: "Download"
      url: "/assets/files/feministclickback-broschuere-2018.pdf"
    contact:
      name: "Contact"
      url: "/en/contact.html"
